### ISSUE TITLE
Wheels for ARM architecture?

### ISSUE THREAD

**Issue by schlegelp** [clbarnes/ncollpyde#18]
Hi Chris,

@paulneuro189 and I were wondering if there was a chance for wheels for ARM architecture (i.e. the new Apple M1 chips)?

Thanks,
Philipp

**Comment by clbarnes** [comment]
I don't think github actions host any M1 runners. It looks like it's possible to draft it out to a 3rd party but it's an additional service and a bit more complicated to set up. I also don't have any way to test M1 builds locally :grimacing:

**Comment by schlegelp** [comment]
Thanks for looking into it! Paul and I managed to get it to compile actually. It's as simple as:

```bash
brew install rust
pip3 install ncollpyde
```

So if it does not (yet) work with GH actions, I probably put this on the back burner for now.

**Comment by aschampion** [comment]
I was considering requisitioning a M1 Mini specifically for the purposes of building and testing our software for this arch. @clbarnes would it be easy to have GH actions call out to something (like a local GitLabCI or such) hosted on such a box? Worse case I guess we could just have it watch tags and publish on its own.

**Comment by aschampion** [comment]
> Yeah, with PEP518, maturin, cargo, and rust's general preference for static linking, local builds are very painless compared to other compiled languages. Glad it's working!

The new manylinux spec is wreaking havoc with anything running on LMB systems or other LTS linux OSes, though. glibc!

**Comment by messense** [comment]
FYI [maturin-action](https://github.com/messense/maturin-action) can do cross compiling for both macOS arm64 wheels and Linux aarch64 wheels, for example,

1. https://github.com/messense/crfs-rs/blob/b1d757b83519a7b4c1ff458bb56f0a625de56ba4/.github/workflows/Python.yml#L31-L34
2. https://github.com/messense/crfs-rs/blob/b1d757b83519a7b4c1ff458bb56f0a625de56ba4/.github/workflows/Python.yml#L105-L120

**Comment by clbarnes** [comment]
Are there any performance implications of wheels built with `--universal2`?

**Comment by messense** [comment]
> Are there any performance implications of wheels built with `--universal2`?

No, it's just a [fat binary](https://en.wikipedia.org/wiki/Universal_binary#Universal_2).

> can --universal2 be safely passed on non-macos OSs?

Yes, it's simply ignored on non-macOS OSs.

**Comment by messense** [comment]
The new release works on my M1 MacBook Pro.

```bash
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C5021h

❯ uname -a
Darwin m1.lan 21.2.0 Darwin Kernel Version 21.2.0: Wed Oct 20 00:23:21 PDT 2021; root:xnu-8019.60.40.0.1~26/RELEASE_ARM64_T8101 arm64

❯ python --version
Python 3.9.2

❯ pip --version
pip 21.3.1 from /Users/messense/.pyenv/versions/3.9.2/envs/test/lib/python3.9/site-packages/pip (python 3.9)

❯ pip install -U ncollpyde
Collecting ncollpyde
  Using cached ncollpyde-0.17.3-cp36-abi3-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (528 kB)
Requirement already satisfied: numpy>=1.16.0 in /Users/messense/.pyenv/versions/3.9.2/envs/test/lib/python3.9/site-packages (from ncollpyde) (1.21.0)
Installing collected packages: ncollpyde
Successfully installed ncollpyde-0.17.3

❯ ipython
Python 3.9.2 (default, Mar 20 2021, 21:34:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ncollpyde

In [2]: exit
```

**Comment by clbarnes** [comment]
Brilliant! Thanks for all your help and the wonderful tool that is maturin/ maturin-action!
