### ISSUE TITLE
Python 3.9 wheels

### ISSUE THREAD

**Issue by clbarnes** [clbarnes/ncollpyde#9]
Building on CI is currently difficult because upstream packages (shapely, scipy) lack wheels. The workarounds for those and additional build time makes it not worth supporting 3.9 at the moment, although it probably works if built locally.

**Comment by clbarnes** [comment]
Just trying it now; pyoctree is what's stopping the simple upgrade, but that's only used for benchmarking so I should just remove it from the build.

**Comment by clbarnes** [comment]
Sausage machine is grinding away now! Having some issues with an intermittent test failure (#13) and README rendering (which is apparently a rejection on pypi now...) so it may be tomorrow, run out of time for tonight.

**Comment by clbarnes** [comment]
We're good! Anything for my user :heart:

**Comment by schlegelp** [comment]
<img width="833" alt="Screenshot 2021-05-10 at 18 42 53" src="https://user-images.githubusercontent.com/7161148/117701800-90bb5c80-b1bf-11eb-943e-88ef885db4a5.png">

Brilliant, thanks a lot!

**Comment by schlegelp** [comment]
Quick question:
`navis`' build on readthedocs is failing because it tries installing `ncollpyde` `0.15.2` from source instead of using the wheel:

```
Searching for ncollpyde>=0.11
Reading https://pypi.org/simple/ncollpyde/
Downloading https://files.pythonhosted.org/packages/fd/37/59d638dc4759e1b33d27ad614789d014aa9c2d696b950c2761f4877f024a/ncollpyde-0.15.2.tar.gz#sha256=9a756393696a7f3d8974a1f9d0ab19cb71b6c0eea31d0855819c0bfa897a097f
Best match: ncollpyde 0.15.2
Processing ncollpyde-0.15.2.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-7f9kdpx2/ncollpyde-0.15.2.tar.gz
```

readthedocs is Python 3.7 and (I think) Ubuntu 18.04.

It used to work with `ncollpyde` `0.14.0` where the wheel is called `ncollpyde-0.14.0-cp37-cp37m-manylinux1_x86_64.whl`. With `0.15.2` the wheel is called `ncollpyde-0.15.2-cp37-cp37m-manylinux_2_24_x86_64.whl` - note the `manylinux_2_24` tag. Correct me if I'm wrong but that tag is for Debian 9-based distributions, right? Any clue why pip on readthedocs wouldn't want to use it? I made sure `pip`, `wheel` and `setuptools` are up-to-date in the build.

**Comment by schlegelp** [comment]
Thanks! I reverted to installing ncollpyde `0.14.0` on rtd, so this is working for the moment.

**Comment by schlegelp** [comment]
Another data point: I had somebody who is using Ubuntu (20.04.1 LTS) via a VM on Windows with the same issue.

**Comment by clbarnes** [comment]
It looks like manylinux_2_24 should work on any system with glibc >=2.24 (released in mid 2016): https://packaging.python.org/specifications/platform-compatibility-tags/#platform-tags-for-common-linux-distributions It doesn't seem likely that rtd or this 20.04 VM are missing that - if they were using musl instead of glibc, it never would have worked. But worth checking.

There is currently a limitation in the metadata packaging standard which means cargo needs to be called just for parsing metadata (if I understand [this issue](https://github.com/PyO3/maturin/issues/563) correctly). There is an [accepted PEP](https://www.python.org/dev/peps/pep-0643/) to resolve that, and [maturin has a PR](https://github.com/PyO3/maturin/pull/564) implementing it, but that PEP has not been implemented by warehouse (which I think is what runs PyPI) which means the PR can't be merged yet. In the meantime, would it be possible to try installing cargo?

**Comment by clbarnes** [comment]
Having a look into this now. It seems the libc package on ubuntu 20.04 is glibc 2.31; for 18.04 it's 2.27; for 16.04 it's 2.23 (not a problem as it's EOL). If cargo is installed on the system, it can pip install from source without issue; although interestingly, if you then remove the cargo package and everything it installs, re-installing from the wheel succeeds but it doesn't work, citing a missing GLIBC.

I can `pip install ncollpyde` fine in my 20.04 VM, even without cargo, as it comes straight from the wheel. With cargo installed, I can build it from the sdist on PyPI.

I suspect there are at least 2 different issues in play here. Readthedocs is failing to find a setup script, which to me suggests it's using a version of pip old enough that it's not PEP518-compliant (<=19, Jan 2019). Collab is failing to read metadata, which could be due to a lack of cargo, or using a libc other than a relatively modern glibc. I'm not sure which the ubuntu VM may be running into.

**Comment by clbarnes** [comment]
Unfortunately it can't be forced to use an older version of (e.g. 2014) due to "libc.so.6 offending symbols: __cxa_thread_atexit_impl@@GLIBC_2.18".

According to that PyPA page, manylinux1 and manylinux2010 are end of life, but manylinux 2014 and 2_24 are "relatively new and is not yet widely recognised by install tools" (although pip has supported it for a year and auditwheel for 6 months). No goldielocks zone apparently.

**Comment by schlegelp** [comment]
I see - many different reasons. I'll keep the outdated pip in mind. Thanks for investigating.

**Comment by clbarnes** [comment]
I am currently pushing out a new version which may resolve any or all of these, thanks to @messense 's contribution which allows manylinux1-compatible wheels to be built.
